import { useState, useEffect } from "react"
import { useNavigate } from "react-router-dom"
import "./UpdateStock.css"
import "./DayReport.css"

const localDay = (d) => {
  const x = new Date(d)
  return `${x.getFullYear()}-${String(x.getMonth() + 1).padStart(2, "0")}-${String(x.getDate()).padStart(2, "0")}`
}
const money = (n) => "Rs " + (Number(n) || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })

function DayReport() {
  const navigate = useNavigate()
  const [user, setUser] = useState(null)
  const [bills, setBills] = useState([])

  useEffect(() => {
    const stored = localStorage.getItem("user")
    if (!stored) { navigate("/signin", { replace: true }); return }
    try {
      const parsed = JSON.parse(stored)
      if (!parsed.token) { navigate("/signin", { replace: true }); return }
      setUser(parsed)
    } catch (_) {
      navigate("/signin", { replace: true })
    }
  }, [navigate])

  useEffect(() => {
    try { setBills(JSON.parse(localStorage.getItem("bills") || "[]")) } catch (_) {}
  }, [])

  if (!user) return null

  const todayKey = localDay(new Date())
  const billDay = (b) => (b.createdAt ? localDay(b.createdAt) : b.date)
  const sum = (arr, k) => arr.reduce((s, b) => s + (Number(b[k]) || 0), 0)

  const todays = bills.filter((b) => billDay(b) === todayKey)
  const totalSales = sum(todays, "amount")
  const vat = sum(todays, "vat")
  const taxable = totalSales - vat
  const cashSales = sum(todays.filter((b) => b.status === "paid"), "amount")
  const creditSales = sum(todays.filter((b) => b.status === "credit"), "amount")
  const creditOutstanding = sum(bills.filter((b) => b.status === "credit"), "amount")

  const summary = [
    { label: "Bills issued", value: String(todays.length) },
    { label: "Total sales", value: money(totalSales) },
    { label: "Taxable amount", value: money(taxable) },
    { label: "VAT 13% (incl.)", value: money(vat) },
    { label: "Paid (cash) sales", value: money(cashSales) },
    { label: "Credit sales", value: money(creditSales) },
  ]

  const dateLabel = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })

  return (
    <div className="us-page">
      <div className="dr-bar ns-no-print">
        <button className="us-btn us-back" onClick={() => navigate("/dashboard")}>Back</button>
        <button className="us-btn us-primary" onClick={() => window.print()}>Print / Save PDF</button>
      </div>

      <div className="report-sheet">
        <div className="rep-head">
          <div className="rep-store">{(user.store_name || "Your Store").toUpperCase()}</div>
          <div className="rep-title">Day Report</div>
          <div className="rep-date">{dateLabel}</div>
        </div>

        <div className="rep-section-label">SUMMARY</div>
        <div className="rep-summary">
          {summary.map((s) => (
            <div className="rep-srow" key={s.label}>
              <span className="rep-skey">{s.label}</span>
              <span className="rep-sval">{s.value}</span>
            </div>
          ))}
          <div className="rep-srow rep-srow-out">
            <span className="rep-skey">Credit outstanding (all dates)</span>
            <span className="rep-sval">{money(creditOutstanding)}</span>
          </div>
        </div>

        <div className="rep-section-label">TODAY'S BILLS</div>
        {todays.length === 0 ? (
          <div className="rep-empty">No bills recorded today.</div>
        ) : (
          <table className="rep-table">
            <thead>
              <tr>
                <th style={{ width: "7%" }}>S.N.</th>
                <th style={{ width: "20%" }}>Bill No.</th>
                <th>Customer</th>
                <th style={{ width: "16%", textAlign: "right" }}>Amount</th>
                <th style={{ width: "14%" }}>Status</th>
                <th style={{ width: "12%" }}>Time</th>
              </tr>
            </thead>
            <tbody>
              {todays.map((b, i) => (
                <tr key={b.id}>
                  <td>{i + 1}</td>
                  <td>{b.id}</td>
                  <td>{b.customer}</td>
                  <td className="num">{money(b.amount)}</td>
                  <td>{b.status === "credit" ? "Credit" : "Paid"}</td>
                  <td>{b.time}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr>
                <td colSpan="3" className="rep-total-label">Total sales</td>
                <td className="num">{money(totalSales)}</td>
                <td colSpan="2"></td>
              </tr>
            </tfoot>
          </table>
        )}

        <div className="rep-foot">
          <span>Generated by {user.name || "—"}</span>
          <span>{new Date().toLocaleString()}</span>
        </div>
      </div>
    </div>
  )
}

export default DayReport
